services:
  postgres:
    container_name: escalasicnvdb
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: escalasicnvdb
      PGDATA: /data/postgres
    volumes: 
      - ./data/pg:/data/postgres


