services:
  postgres:
    container_name: escalasicnvdb
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: escalasicnvdb
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: escalasicnv-app
    env_file: ".env"
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  postgres-data:


networks:
  app-network:
    driver: bridge
